### ISSUE TITLE
Make does not compile bibliography, references  and header correctly

### ISSUE THREAD

**Issue by RedHilarious** [ReScience/RC-2020#11]
# Referring to our code in PR #9.

When trying to run the command make from the journal folder, we are having some trouble. 
Here a list of the issues I can see from the [`make-build.log`](https://pastebin.com/PLJzL1Tf) and [`article.log`](https://pastebin.com/Pj0GitzP):

## Bibliography compilation fails due to missing article.bbl
(from [`article.log`](https://pastebin.com/Pj0GitzP))

I was assuming the Makefile automatically also runs bibtex, but according to the logs it does not. Do we manually have to run the Latex compile / bibtex pipeline before we run `make`?

```
ackage biblatex Info: XeTeX detected.
(biblatex)             Assuming input encoding 'utf8'.
Package biblatex Info: Automatic encoding selection.
(biblatex)             Assuming data encoding 'utf8'.
Package biblatex Info: Document encoding is UTF8 ....
Package biblatex Info: ... and expl3
(biblatex)             2021-02-18 L3 programming layer (loader) 
(biblatex)             is new enough (at least 2020/04/06),
(biblatex)             setting 'casechanger=expl3'.

(/usr/local/texlive/2021/texmf-dist/tex/latex/biblatex/blx-case-expl3.sty
Package: blx-case-expl3 2020/12/31 v3.16 expl3 case changing code for biblatex
)
\openout6 = `article.bcf'.

Package biblatex Info: Trying to load bibliographic data...
Package biblatex Info: ... file 'article.bbl' not found.

No file article.bbl.
Package biblatex Info: Reference section=0 on input line 5.
Package biblatex Info: Reference segment=0 on input line 5.
(./header.tex
```

## References are undefined
I am unaware why this might be happening.

```
LaTeX Warning: Reference `tab:classification results' on page 7 undefined on in
put line 328.

[7] [8]

LaTeX Warning: Reference `tab:Authors seq-to-seq synth results' on page 9 undef
ined on input line 331.

... 

LaTeX Warning: There were undefined references.
```

## Header not formatted correctly

<img width="701" alt="Screenshot 2021-04-17 at 01 55 45" src="https://user-images.githubusercontent.com/8261902/115095074-2b59b000-9f20-11eb-9b7f-21aa2664b24f.png">

I also added the currently compiled `article.pdf` to the repo, so that you can also have a look at the visual issues. Thanks for your help.

**Comment by koustuvsinha** [comment]
Added my comments to the PR. I think fixing those two points should solve the issue.

**Comment by RedHilarious** [comment]
As commented in the PR, issues where solved.
