### ISSUE TITLE
Permission denied while cloning the repo

### ISSUE THREAD

**Issue by asdas1505** [ReScience/RC-2020#14]
Following is the message shown after cloning 

Please make sure you have the correct access rights and the repository exists.
fatal: clone of 'git@github.com:ReScience/template.git' into submodule path 'D:/ MLRC Submission/Camera Ready/RC-2020/template' failed Failed to clone 'template'. Retry scheduled Cloning into 'D:/MLRC Submission/Camera Ready/RC-2020/template'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
fatal: clone of 'git@github.com:ReScience/template.git' into submodule path 'D:/ MLRC Submission/Camera Ready/RC2020/template' failed
Failed to clone 'template' a second time, aborting

**Comment by koustuvsinha** [comment]
This is strange.. can you try cloning through https? `git clone https://github.com/ReScience/RC-2020.git --recursive` ?

**Comment by asdas1505** [comment]
Following message pops up while cloning the library. 

[
<img width="455" alt="cloning_problem" src="https://user-images.githubusercontent.com/47027190/115294657-7e2ca500-a176-11eb-9f81-cb1731543d31.PNG">
](url)

**Comment by koustuvsinha** [comment]
Yes, this type of message is common in the `git@` protocol, all you need to do is type 'yes'.  If it doesn't work, please edit the .gitmodules file (https://github.com/ReScience/RC-2020/blob/main/.gitmodules) and replace the following line:

```
[submodule "template"]
	path = template
	url = https://github.com:ReScience/template.git
```

[Read this too](https://stackoverflow.com/a/33072867/2861269) - hope this helps.

**Comment by asdas1505** [comment]
Modifying .gitmodules helped. Thanks
