### ISSUE TITLE
\citeauthor{}

### ISSUE THREAD

**Issue by noudcorten** [ReScience/RC-2020#26]
Hi,

In our original code we use \citeauthor{} to cite the authors of the corresponding paper instead of referencing just the paper. This does compile correctly in the openreview folder, but not in the journal folder.

**Openreview version:**
<img width="854" alt="Schermafbeelding 2021-04-22 om 17 36 08" src="https://user-images.githubusercontent.com/44836798/115742702-3d5ca800-a391-11eb-923e-0bfdcfb59330.png">

**Journal version:**
<img width="773" alt="Schermafbeelding 2021-04-22 om 17 37 27" src="https://user-images.githubusercontent.com/44836798/115743000-83b20700-a391-11eb-988b-260421645f59.png">

Can someone help with this issue?

**Comment by koustuvsinha** [comment]
Please use `citet` instead of `citeauthor`.

**Comment by noudcorten** [comment]
@koustuvsinha Thanks!
