### ISSUE TITLE
Makefile Error

### ISSUE THREAD

**Issue by prateekstark** [ReScience/RC-2020#32]
Latexmk: Non-existent bbl file 'article.bbl'
 No file article.bbl.
Latexmk: References changed.
Latexmk: Log file says output to 'article.pdf'
Latexmk: List of undefined refs and citations:
  Citation 'r1' on page 1 undefined on input line 4
  Citation 'r10' on page 5 undefined on input line 107
  Citation 'r10' on page 7 undefined on input line 348
  Citation 'r11' on page 4 undefined on input line 104
  Citation 'r11' on page 5 undefined on input line 107
  Citation 'r12' on page 5 undefined on input line 107
  Citation 'r3' on page 9 undefined on input line 453
  Citation 'r6' on page 3 undefined on input line 73
  Citation 'r7' on page 4 undefined on input line 85
  Citation 'r8' on page 4 undefined on input line 104
  Citation 'r8' on page 5 undefined on input line 109
  Citation 'r8' on page 6 undefined on input line 300
  Citation 'r8' on page 6 undefined on input line 311
  Citation 'r9' on page 5 undefined on input line 107
  Citation 'r9' on page 7 undefined on input line 348
  Reference `alg1' on page 8 undefined on input line 440
  Reference `fig3' on page 7 undefined on input line 348
  Reference `fig4' on page 7 undefined on input line 348
  Reference `fig5' on page 7 undefined on input line 391
  Reference `table1' on page 5 undefined on input line 121
  Reference `table1' on page 5 undefined on input line 189
  Reference `table1' on page 7 undefined on input line 391
  Reference `table5' on page 7 undefined on input line 391
Latexmk: 'pdflatex': source file 'article.bbl' doesn't exist. I'll try making it...
------------
Running 'make "article.bbl"'
------------
make[1]: Entering directory '/home/stark/Projects/MLRC2020/openreview/last_attempt/RC-2020/garg2021re/journal'
make[1]: *** No rule to make target 'article.bbl'.  Stop.
make[1]: Leaving directory '/home/stark/Projects/MLRC2020/openreview/last_attempt/RC-2020/garg2021re/journal'
Latexmk: Summary of warnings:
  Latex failed to resolve 8 reference(s)
  Latex failed to resolve 16 citation(s)
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Makefile:30: recipe for target 'article.pdf' failed
make: *** [article.pdf] Error 12

**Comment by koustuvsinha** [comment]
Closing this as its resolved in #37
